// File auto-generated by NGFullscreenBindingsWindow.
using UnityEditor;

namespace NGToolsEditor.NGFullscreenBindings
{
	public static class ExternalNGFullscreenBindings
	{
		[TypeWitness("UnityEditor.SceneView,UnityEditor")]
		public const string	F1 = "Scene _";

		[TypeWitness("UnityEditor.GameView,UnityEditor")]
		public const string	F2 = "Game _";

		[TypeWitness("UnityEditor.InspectorWindow,UnityEditor")]
		public const string	F3 = "Inspector _";

		[TypeWitness("UnityEditor.SceneHierarchyWindow,UnityEditor")]
		public const string	F4 = "Hierarchy _";

		[TypeWitness("UnityEditor.ProjectBrowser,UnityEditor")]
		public const string	F5 = "Project _";

		[TypeWitness("UnityEditor.AnimationWindow,UnityEditor")]
		public const string	F6 = "Animation _";

		[TypeWitness("UnityEditor.ProfilerWindow,UnityEditor")]
		public const string	F7 = "Profiler _";

		[TypeWitness("UnityEditor.AudioMixerWindow,UnityEditor")]
		public const string	F8 = "Audio Mixer _";

		[TypeWitness("UnityEditor.AssetStoreWindow,UnityEditor")]
		public const string	F9 = "Asset Store _";

		[TypeWitness("")]
		public const string	F10 = " _";

		[TypeWitness("")]
		public const string	F11 = " _";

		[TypeWitness("NGToolsEditor.NGConsole.NGConsoleWindow,NGConsoleEditor")]
		public const string	F12 = "NG Console _";

		[MenuItem(NGFullscreenBindingsWindow.MenuItemPath + ExternalNGFullscreenBindings.F12 + "F12", priority = Constants.MenuItemPriority + 912)]
		public static void	ToggleFullscreenF12()
		{
			NGFullscreenBindingsWindow.ToggleFullscreen(12);
		}
	}
}